/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\admin\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-7a1547af",
    path: "/mysql/introduce.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7a1547af").then(next)
    },
  },
  {
    name: "v-476b2aaf",
    path: "/mysql/node_engine.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-476b2aaf").then(next)
    },
  },
  {
    name: "v-1c4118c2",
    path: "/nested/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c4118c2").then(next)
    },
  },
  {
    path: "/nested/index.html",
    redirect: "/nested/"
  },
  {
    name: "v-4964e974",
    path: "/mysql/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4964e974").then(next)
    },
  },
  {
    path: "/mysql/index.html",
    redirect: "/mysql/"
  },
  {
    name: "v-09f44a2f",
    path: "/mysql/operate_sql.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-09f44a2f").then(next)
    },
  },
  {
    name: "v-d8ffd67c",
    path: "/timeLine/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d8ffd67c").then(next)
    },
  },
  {
    path: "/timeLine/index.html",
    redirect: "/timeLine/"
  },
  {
    name: "v-3d2d673c",
    path: "/node/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3d2d673c").then(next)
    },
  },
  {
    path: "/node/index.html",
    redirect: "/node/"
  },
  {
    name: "v-92fb9f62",
    path: "/web/H5/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-92fb9f62").then(next)
    },
  },
  {
    path: "/web/H5/index.html",
    redirect: "/web/H5/"
  },
  {
    name: "v-5bc2f40e",
    path: "/web/H5/svg.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5bc2f40e").then(next)
    },
  },
  {
    name: "v-05a5bba2",
    path: "/web/React/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-05a5bba2").then(next)
    },
  },
  {
    path: "/web/React/index.html",
    redirect: "/web/React/"
  },
  {
    name: "v-01e106c2",
    path: "/web/React/chess.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01e106c2").then(next)
    },
  },
  {
    name: "v-a1a12a22",
    path: "/web/advanced/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a1a12a22").then(next)
    },
  },
  {
    path: "/web/advanced/index.html",
    redirect: "/web/advanced/"
  },
  {
    name: "v-511ddc7c",
    path: "/web/es6/ArrayBuffer.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-511ddc7c").then(next)
    },
  },
  {
    name: "v-3e6fdd30",
    path: "/web/advanced/prototype.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3e6fdd30").then(next)
    },
  },
  {
    name: "v-766fc85d",
    path: "/web/es6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-766fc85d").then(next)
    },
  },
  {
    path: "/web/es6/index.html",
    redirect: "/web/es6/"
  },
  {
    name: "v-a8d476fc",
    path: "/web/es6/es7_decorator.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a8d476fc").then(next)
    },
  },
  {
    name: "v-86193a14",
    path: "/web/advanced/inherit.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-86193a14").then(next)
    },
  },
  {
    name: "v-0c94ce02",
    path: "/web/es6/front_end_modul.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c94ce02").then(next)
    },
  },
  {
    name: "v-6fc3fde2",
    path: "/web/es6/ts_config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6fc3fde2").then(next)
    },
  },
  {
    name: "v-5597620f",
    path: "/web/ts/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5597620f").then(next)
    },
  },
  {
    path: "/web/ts/index.html",
    redirect: "/web/ts/"
  },
  {
    name: "v-05413ae1",
    path: "/web/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-05413ae1").then(next)
    },
  },
  {
    path: "/web/vue/index.html",
    redirect: "/web/vue/"
  },
  {
    name: "v-324bfd7c",
    path: "/web/ts/install.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-324bfd7c").then(next)
    },
  },
  {
    name: "v-b37131fc",
    path: "/web/vue/vuePress_deploy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b37131fc").then(next)
    },
  },
  {
    name: "v-4ab03f75",
    path: "/zh/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4ab03f75").then(next)
    },
  },
  {
    path: "/zh/guide/index.html",
    redirect: "/zh/guide/"
  },
  {
    name: "v-82487002",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-82487002").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-70b2b9a2",
    path: "/friendLink/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-70b2b9a2").then(next)
    },
  },
  {
    path: "/friendLink/index.html",
    redirect: "/friendLink/"
  },
  {
    name: "v-e66ed5dc",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e66ed5dc").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-651d923c",
    path: "/guide/js/test.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-651d923c").then(next)
    },
  },
  {
    name: "v-b3306848",
    path: "/guide/ts/test01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b3306848").then(next)
    },
  },
  {
    name: "v-a16ed662",
    path: "/guide/ts/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a16ed662").then(next)
    },
  },
  {
    path: "/guide/ts/index.html",
    redirect: "/guide/ts/"
  },
  {
    name: "v-2c4cf17c",
    path: "/guide/ts/test02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2c4cf17c").then(next)
    },
  },
  {
    name: "v-9b9bd1c8",
    path: "/guide/ts/test03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9b9bd1c8").then(next)
    },
  },
  {
    name: "v-4ed5b891",
    path: "/guide/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4ed5b891").then(next)
    },
  },
  {
    path: "/guide/vue/index.html",
    redirect: "/guide/vue/"
  },
  {
    name: "v-5dcd1f24",
    path: "/guide/vue/test02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5dcd1f24").then(next)
    },
  },
  {
    name: "v-64e976a0",
    path: "/guide/vue/test01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64e976a0").then(next)
    },
  },
  {
    name: "v-56b0c7a8",
    path: "/guide/vue/test03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-56b0c7a8").then(next)
    },
  },
  {
    name: "v-da26df3c",
    path: "/java/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-da26df3c").then(next)
    },
  },
  {
    path: "/java/index.html",
    redirect: "/java/"
  },
  {
    name: "v-7f5ae9a2",
    path: "/mysql/date_type.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f5ae9a2").then(next)
    },
  },
  {
    name: "v-e2bde822",
    path: "/mysql/db_base_table.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e2bde822").then(next)
    },
  },
  {
    name: "v-f60c83e2",
    path: "/mysql/dowloadAndinstall.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f60c83e2").then(next)
    },
  },
  {
    name: "v-33db0ae2",
    path: "/mysql/indexes.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-33db0ae2").then(next)
    },
  },
  {
    name: "v-6967dbaf",
    path: "/mysql/insert_update.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6967dbaf").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]