/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/limyt/.config/yarn/global/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-48e5b0c2",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-48e5b0c2").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-a1b6df9c",
    path: "/friendLink/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a1b6df9c").then(next)
    },
  },
  {
    path: "/friendLink/index.html",
    redirect: "/friendLink/"
  },
  {
    name: "v-5a905df9",
    path: "/guide/JS/test.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5a905df9").then(next)
    },
  },
  {
    name: "v-e1af29b0",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e1af29b0").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-2976bd9c",
    path: "/java/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2976bd9c").then(next)
    },
  },
  {
    path: "/java/index.html",
    redirect: "/java/"
  },
  {
    name: "v-44a53d48",
    path: "/mysql/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-44a53d48").then(next)
    },
  },
  {
    path: "/mysql/index.html",
    redirect: "/mysql/"
  },
  {
    name: "v-a078ac4e",
    path: "/mysql/src/dowloadAndinstall.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a078ac4e").then(next)
    },
  },
  {
    name: "v-62346ff9",
    path: "/mysql/src/introduce.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-62346ff9").then(next)
    },
  },
  {
    name: "v-03495a6c",
    path: "/mysql/src/%E6%95%B0%E6%8D%AE%E5%BA%93%E5%9F%BA%E6%9C%AC%E6%93%8D%E4%BD%9C.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-03495a6c").then(next)
    },
  },
  {
    path: "/mysql/src/数据库基本操作.html",
    redirect: "/mysql/src/%E6%95%B0%E6%8D%AE%E5%BA%93%E5%9F%BA%E6%9C%AC%E6%93%8D%E4%BD%9C.html"
  },
  {
    path: "/mysql/src/数据库基本操作.html",
    redirect: "/mysql/src/%E6%95%B0%E6%8D%AE%E5%BA%93%E5%9F%BA%E6%9C%AC%E6%93%8D%E4%BD%9C.html"
  },
  {
    name: "v-c15b9e5c",
    path: "/nested/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c15b9e5c").then(next)
    },
  },
  {
    path: "/nested/index.html",
    redirect: "/nested/"
  },
  {
    name: "v-39c15d32",
    path: "/node/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-39c15d32").then(next)
    },
  },
  {
    path: "/node/index.html",
    redirect: "/node/"
  },
  {
    name: "v-6735c412",
    path: "/timeLine/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6735c412").then(next)
    },
  },
  {
    path: "/timeLine/index.html",
    redirect: "/timeLine/"
  },
  {
    name: "v-02b020b2",
    path: "/web/H5/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-02b020b2").then(next)
    },
  },
  {
    path: "/web/H5/index.html",
    redirect: "/web/H5/"
  },
  {
    name: "v-508a6cea",
    path: "/web/H5/svg.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-508a6cea").then(next)
    },
  },
  {
    name: "v-1592f1d8",
    path: "/web/React/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1592f1d8").then(next)
    },
  },
  {
    path: "/web/React/index.html",
    redirect: "/web/React/"
  },
  {
    name: "v-320fc539",
    path: "/web/React/chess.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-320fc539").then(next)
    },
  },
  {
    name: "v-7b1399f9",
    path: "/web/es6/ArrayBuffer.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b1399f9").then(next)
    },
  },
  {
    name: "v-013aa874",
    path: "/web/es6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-013aa874").then(next)
    },
  },
  {
    path: "/web/es6/index.html",
    redirect: "/web/es6/"
  },
  {
    name: "v-2dbb5939",
    path: "/web/es6/es7_decorator.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2dbb5939").then(next)
    },
  },
  {
    name: "v-23e32f39",
    path: "/web/es6/front_end_modul.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-23e32f39").then(next)
    },
  },
  {
    name: "v-b72d8cce",
    path: "/web/es6/ts_config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b72d8cce").then(next)
    },
  },
  {
    name: "v-e397c36c",
    path: "/web/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e397c36c").then(next)
    },
  },
  {
    path: "/web/vue/index.html",
    redirect: "/web/vue/"
  },
  {
    name: "v-84d46f8e",
    path: "/web/vue/vuePress_deploy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-84d46f8e").then(next)
    },
  },
  {
    name: "v-699b5b5c",
    path: "/zh/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-699b5b5c").then(next)
    },
  },
  {
    path: "/zh/guide/index.html",
    redirect: "/zh/guide/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]