/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\admin\\AppData\\Local\\Yarn\\Data\\global\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-82487002",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-82487002").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-70b2b9a2",
    path: "/friendLink/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-70b2b9a2").then(next)
    },
  },
  {
    path: "/friendLink/index.html",
    redirect: "/friendLink/"
  },
  {
    name: "v-e395db88",
    path: "/guide/JS/test.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e395db88").then(next)
    },
  },
  {
    name: "v-e66ed5dc",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e66ed5dc").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-da26df3c",
    path: "/java/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-da26df3c").then(next)
    },
  },
  {
    path: "/java/index.html",
    redirect: "/java/"
  },
  {
    name: "v-4964e974",
    path: "/mysql/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4964e974").then(next)
    },
  },
  {
    path: "/mysql/index.html",
    redirect: "/mysql/"
  },
  {
    name: "v-d9e02d7c",
    path: "/mysql/src/introduce.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d9e02d7c").then(next)
    },
  },
  {
    name: "v-14fd7122",
    path: "/mysql/src/dowloadAndinstall.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-14fd7122").then(next)
    },
  },
  {
    name: "v-1c4118c2",
    path: "/nested/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c4118c2").then(next)
    },
  },
  {
    path: "/nested/index.html",
    redirect: "/nested/"
  },
  {
    name: "v-d8ffd67c",
    path: "/timeLine/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d8ffd67c").then(next)
    },
  },
  {
    path: "/timeLine/index.html",
    redirect: "/timeLine/"
  },
  {
    name: "v-3d2d673c",
    path: "/node/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3d2d673c").then(next)
    },
  },
  {
    path: "/node/index.html",
    redirect: "/node/"
  },
  {
    name: "v-92fb9f62",
    path: "/web/H5/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-92fb9f62").then(next)
    },
  },
  {
    path: "/web/H5/index.html",
    redirect: "/web/H5/"
  },
  {
    name: "v-05a5bba2",
    path: "/web/React/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-05a5bba2").then(next)
    },
  },
  {
    path: "/web/React/index.html",
    redirect: "/web/React/"
  },
  {
    name: "v-5bc2f40e",
    path: "/web/H5/svg.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5bc2f40e").then(next)
    },
  },
  {
    name: "v-01e106c2",
    path: "/web/React/chess.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01e106c2").then(next)
    },
  },
  {
    name: "v-511ddc7c",
    path: "/web/es6/ArrayBuffer.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-511ddc7c").then(next)
    },
  },
  {
    name: "v-766fc85d",
    path: "/web/es6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-766fc85d").then(next)
    },
  },
  {
    path: "/web/es6/index.html",
    redirect: "/web/es6/"
  },
  {
    name: "v-a8d476fc",
    path: "/web/es6/es7_decorator.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a8d476fc").then(next)
    },
  },
  {
    name: "v-0c94ce02",
    path: "/web/es6/front_end_modul.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c94ce02").then(next)
    },
  },
  {
    name: "v-6fc3fde2",
    path: "/web/es6/ts_config.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6fc3fde2").then(next)
    },
  },
  {
    name: "v-05413ae1",
    path: "/web/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-05413ae1").then(next)
    },
  },
  {
    path: "/web/vue/index.html",
    redirect: "/web/vue/"
  },
  {
    name: "v-b37131fc",
    path: "/web/vue/vuePress_deploy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b37131fc").then(next)
    },
  },
  {
    name: "v-4ab03f75",
    path: "/zh/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4ab03f75").then(next)
    },
  },
  {
    path: "/zh/guide/index.html",
    redirect: "/zh/guide/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]