/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "myBlog",
  "description": "myBlogmyBlogmyBlogmyBlog",
  "base": "/myBlog/",
  "headTags": [
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ],
    [
      "link",
      {
        "rel": "icon",
        "href": "favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/hero.png",
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2020-present  mzmuping"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-82487002",
      "path": "/",
      "lastUpdated": "11/19/2021, 6:37:52 PM"
    },
    {
      "title": "github 提交失败",
      "frontmatter": {},
      "regularPath": "/error/git_error.html",
      "relativePath": "error/git_error.md",
      "key": "v-6b0846ef",
      "path": "/error/git_error.html",
      "headers": [
        {
          "level": 3,
          "title": "github 提交失败",
          "slug": "github-提交失败"
        },
        {
          "level": 3,
          "title": "git报错ssh",
          "slug": "git报错ssh"
        }
      ],
      "lastUpdated": "4/24/2022, 5:39:33 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-e66ed5dc",
      "path": "/guide/",
      "lastUpdated": "3/6/2021, 4:40:28 PM"
    },
    {
      "title": "错误总结",
      "frontmatter": {
        "title": "错误总结",
        "date": "2021-01-21T00:00:00.000Z",
        "categories": [
          "git"
        ],
        "tags": [
          "git",
          "git"
        ]
      },
      "regularPath": "/error/",
      "relativePath": "error/README.md",
      "key": "v-4ccdc1fa",
      "path": "/error/",
      "headers": [
        {
          "level": 3,
          "title": "错误总结",
          "slug": "错误总结"
        }
      ],
      "lastUpdated": "1/21/2022, 6:06:43 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/friendLink/",
      "relativePath": "friendLink/README.md",
      "key": "v-70b2b9a2",
      "path": "/friendLink/",
      "lastUpdated": "3/6/2021, 4:40:28 PM"
    },
    {
      "title": "es7之修饰器",
      "frontmatter": {
        "title": "es7之修饰器",
        "date": "2019-8-17",
        "categories": null,
        "sidebarDepth": 2
      },
      "regularPath": "/guide/js/test.html",
      "relativePath": "guide/js/test.md",
      "key": "v-651d923c",
      "path": "/guide/js/test.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/ts/",
      "relativePath": "guide/ts/README.md",
      "key": "v-a16ed662",
      "path": "/guide/ts/",
      "lastUpdated": "1/11/2022, 3:57:00 PM"
    },
    {
      "title": "测试01",
      "frontmatter": {
        "title": "测试01",
        "date": "2021-11-25T00:00:00.000Z",
        "categories": [
          "frontend"
        ],
        "tags": [
          "mysql",
          "索引"
        ]
      },
      "regularPath": "/guide/ts/test01.html",
      "relativePath": "guide/ts/test01.md",
      "key": "v-b3306848",
      "path": "/guide/ts/test01.html",
      "headers": [
        {
          "level": 2,
          "title": "测试01 - Typescript",
          "slug": "测试01-typescript"
        }
      ],
      "lastUpdated": "1/11/2022, 3:57:00 PM"
    },
    {
      "title": "测试02",
      "frontmatter": {
        "title": "测试02",
        "date": "2021-11-25T00:00:00.000Z",
        "categories": [
          "frontend"
        ],
        "tags": [
          "mysql",
          "索引"
        ]
      },
      "regularPath": "/guide/ts/test02.html",
      "relativePath": "guide/ts/test02.md",
      "key": "v-2c4cf17c",
      "path": "/guide/ts/test02.html",
      "headers": [
        {
          "level": 2,
          "title": "测试01 - Typescript",
          "slug": "测试01-typescript"
        }
      ],
      "lastUpdated": "1/11/2022, 3:57:00 PM"
    },
    {
      "title": "测试03",
      "frontmatter": {
        "title": "测试03",
        "date": "2021-11-25T00:00:00.000Z",
        "categories": [
          "frontend"
        ],
        "tags": [
          "mysql",
          "索引"
        ]
      },
      "regularPath": "/guide/ts/test03.html",
      "relativePath": "guide/ts/test03.md",
      "key": "v-9b9bd1c8",
      "path": "/guide/ts/test03.html",
      "headers": [
        {
          "level": 2,
          "title": "测试01 - Typescript",
          "slug": "测试01-typescript"
        }
      ],
      "lastUpdated": "1/11/2022, 3:57:00 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/vue/",
      "relativePath": "guide/vue/README.md",
      "key": "v-4ed5b891",
      "path": "/guide/vue/",
      "lastUpdated": "1/11/2022, 3:57:00 PM"
    },
    {
      "title": "测试01",
      "frontmatter": {
        "title": "测试01",
        "date": "2021-11-25T00:00:00.000Z",
        "categories": [
          "frontend"
        ],
        "tags": [
          "mysql",
          "索引"
        ]
      },
      "regularPath": "/guide/vue/test01.html",
      "relativePath": "guide/vue/test01.md",
      "key": "v-64e976a0",
      "path": "/guide/vue/test01.html",
      "headers": [
        {
          "level": 2,
          "title": "test01",
          "slug": "test01"
        },
        {
          "level": 3,
          "title": "test01--1",
          "slug": "test01-1"
        }
      ],
      "lastUpdated": "1/11/2022, 3:57:00 PM"
    },
    {
      "title": "test02",
      "frontmatter": {},
      "regularPath": "/guide/vue/test02.html",
      "relativePath": "guide/vue/test02.md",
      "key": "v-5dcd1f24",
      "path": "/guide/vue/test02.html",
      "headers": [
        {
          "level": 2,
          "title": "test02",
          "slug": "test02"
        },
        {
          "level": 3,
          "title": "test02--1",
          "slug": "test02-1"
        }
      ],
      "lastUpdated": "1/11/2022, 3:57:00 PM"
    },
    {
      "title": "test03",
      "frontmatter": {},
      "regularPath": "/guide/vue/test03.html",
      "relativePath": "guide/vue/test03.md",
      "key": "v-56b0c7a8",
      "path": "/guide/vue/test03.html",
      "headers": [
        {
          "level": 2,
          "title": "test03",
          "slug": "test03"
        },
        {
          "level": 3,
          "title": "test03--1",
          "slug": "test03-1"
        }
      ],
      "lastUpdated": "1/11/2022, 3:57:00 PM"
    },
    {
      "frontmatter": {
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/"
      },
      "regularPath": "/java/",
      "relativePath": "java/README.md",
      "key": "v-da26df3c",
      "path": "/java/",
      "lastUpdated": "3/6/2021, 4:40:28 PM"
    },
    {
      "title": "数据库数据类型",
      "frontmatter": {},
      "regularPath": "/mysql/date_type.html",
      "relativePath": "mysql/date_type.md",
      "key": "v-7f5ae9a2",
      "path": "/mysql/date_type.html",
      "headers": [
        {
          "level": 2,
          "title": "数据库数据类型",
          "slug": "数据库数据类型"
        },
        {
          "level": 3,
          "title": "数值类",
          "slug": "数值类"
        }
      ],
      "lastUpdated": "11/18/2021, 6:31:41 PM"
    },
    {
      "title": "数据库操作步骤",
      "frontmatter": {},
      "regularPath": "/mysql/db_base_table.html",
      "relativePath": "mysql/db_base_table.md",
      "key": "v-e2bde822",
      "path": "/mysql/db_base_table.html",
      "headers": [
        {
          "level": 3,
          "title": "数据库操作步骤",
          "slug": "数据库操作步骤"
        },
        {
          "level": 2,
          "title": "数据表基本操作",
          "slug": "数据表基本操作"
        },
        {
          "level": 3,
          "title": "1、创建表的语法形式",
          "slug": "_1、创建表的语法形式"
        },
        {
          "level": 3,
          "title": "2、使用主键约束",
          "slug": "_2、使用主键约束"
        },
        {
          "level": 3,
          "title": "3、使用外键约束",
          "slug": "_3、使用外键约束"
        },
        {
          "level": 3,
          "title": "4、使用非空约束",
          "slug": "_4、使用非空约束"
        },
        {
          "level": 3,
          "title": "5、使用唯一性约束",
          "slug": "_5、使用唯一性约束"
        },
        {
          "level": 3,
          "title": "5、使用默认值约束",
          "slug": "_5、使用默认值约束"
        },
        {
          "level": 3,
          "title": "6、设置表属性值自动增加",
          "slug": "_6、设置表属性值自动增加"
        },
        {
          "level": 2,
          "title": "操作数据表",
          "slug": "操作数据表"
        },
        {
          "level": 3,
          "title": "查看数据表定义信息",
          "slug": "查看数据表定义信息"
        },
        {
          "level": 3,
          "title": "修改表名",
          "slug": "修改表名"
        },
        {
          "level": 3,
          "title": "修改字段的数据类型",
          "slug": "修改字段的数据类型"
        },
        {
          "level": 3,
          "title": "修改字段名称",
          "slug": "修改字段名称"
        },
        {
          "level": 3,
          "title": "添加字段名",
          "slug": "添加字段名"
        },
        {
          "level": 3,
          "title": "删除数据表字段",
          "slug": "删除数据表字段"
        },
        {
          "level": 3,
          "title": "调整字段位置",
          "slug": "调整字段位置"
        },
        {
          "level": 3,
          "title": "删除外键约束",
          "slug": "删除外键约束"
        },
        {
          "level": 3,
          "title": "删除数据表",
          "slug": "删除数据表"
        }
      ],
      "lastUpdated": "11/29/2021, 2:26:38 PM"
    },
    {
      "title": "MySQL安装及基本使用教程",
      "frontmatter": {},
      "regularPath": "/mysql/dowloadAndinstall.html",
      "relativePath": "mysql/dowloadAndinstall.md",
      "key": "v-f60c83e2",
      "path": "/mysql/dowloadAndinstall.html",
      "headers": [
        {
          "level": 2,
          "title": "MySQL安装及基本使用教程",
          "slug": "mysql安装及基本使用教程"
        },
        {
          "level": 3,
          "title": "下载MySQL",
          "slug": "下载mysql"
        },
        {
          "level": 2,
          "title": "测试msyql",
          "slug": "测试msyql"
        },
        {
          "level": 3,
          "title": "连接Navicat 报错",
          "slug": "连接navicat-报错"
        }
      ],
      "lastUpdated": "11/19/2021, 6:37:52 PM"
    },
    {
      "title": "索引",
      "frontmatter": {
        "title": "索引",
        "date": "2021-11-25T00:00:00.000Z",
        "categories": [
          "frontend"
        ],
        "tags": [
          "mysql",
          "索引"
        ]
      },
      "regularPath": "/mysql/indexes.html",
      "relativePath": "mysql/indexes.md",
      "key": "v-33db0ae2",
      "path": "/mysql/indexes.html",
      "headers": [
        {
          "level": 2,
          "title": "索引的含义和特点",
          "slug": "索引的含义和特点"
        },
        {
          "level": 3,
          "title": "索引的分类",
          "slug": "索引的分类"
        },
        {
          "level": 3,
          "title": "索引的设计原则",
          "slug": "索引的设计原则"
        },
        {
          "level": 2,
          "title": "创建表的时候创建索引",
          "slug": "创建表的时候创建索引"
        }
      ],
      "lastUpdated": "11/29/2021, 2:22:20 PM"
    },
    {
      "title": "插入，修改，删除",
      "frontmatter": {
        "title": "插入，修改，删除",
        "date": "2021-11-25T00:00:00.000Z",
        "categories": [
          "frontend"
        ],
        "tags": [
          "mysql",
          "sql"
        ]
      },
      "regularPath": "/mysql/insert_update.html",
      "relativePath": "mysql/insert_update.md",
      "key": "v-6967dbaf",
      "path": "/mysql/insert_update.html",
      "headers": [
        {
          "level": 2,
          "title": "插入数据",
          "slug": "插入数据"
        },
        {
          "level": 3,
          "title": "更新数据",
          "slug": "更新数据"
        },
        {
          "level": 3,
          "title": "删除数据",
          "slug": "删除数据"
        }
      ],
      "lastUpdated": "1/11/2022, 3:57:00 PM"
    },
    {
      "title": "文件配置",
      "frontmatter": {
        "title": "文件配置",
        "date": "2022-01-11T00:00:00.000Z",
        "categories": [
          "frontend"
        ],
        "tags": [
          "mysql",
          "索引"
        ]
      },
      "regularPath": "/mysql/introduce.html",
      "relativePath": "mysql/introduce.md",
      "key": "v-7a1547af",
      "path": "/mysql/introduce.html",
      "headers": [
        {
          "level": 2,
          "title": "文件配置",
          "slug": "文件配置"
        },
        {
          "level": 2,
          "title": "启动mysql",
          "slug": "启动mysql"
        },
        {
          "level": 2,
          "title": "关闭",
          "slug": "关闭"
        },
        {
          "level": 2,
          "title": "MySQL连接管理",
          "slug": "mysql连接管理"
        },
        {
          "level": 2,
          "title": "切换数据库",
          "slug": "切换数据库"
        },
        {
          "level": 3,
          "title": "创建用户",
          "slug": "创建用户"
        },
        {
          "level": 3,
          "title": "查看用户",
          "slug": "查看用户"
        },
        {
          "level": 3,
          "title": "修改用户密码",
          "slug": "修改用户密码"
        },
        {
          "level": 3,
          "title": "删除用户",
          "slug": "删除用户"
        },
        {
          "level": 3,
          "title": "查看权限",
          "slug": "查看权限"
        },
        {
          "level": 3,
          "title": "授予权限",
          "slug": "授予权限"
        },
        {
          "level": 3,
          "title": "MySQL各种权限：",
          "slug": "mysql各种权限"
        },
        {
          "level": 3,
          "title": "MySQL常用的命令",
          "slug": "mysql常用的命令"
        }
      ],
      "lastUpdated": "1/11/2022, 3:57:00 PM"
    },
    {
      "title": "数据库 增删改查",
      "frontmatter": {},
      "regularPath": "/mysql/node_engine.html",
      "relativePath": "mysql/node_engine.md",
      "key": "v-476b2aaf",
      "path": "/mysql/node_engine.html",
      "headers": [
        {
          "level": 2,
          "title": "数据库 增删改查",
          "slug": "数据库-增删改查"
        },
        {
          "level": 2,
          "title": "安装node版Mysql数据库的驱动模块",
          "slug": "安装node版mysql数据库的驱动模块"
        },
        {
          "level": 3,
          "title": "案例：",
          "slug": "案例"
        },
        {
          "level": 2,
          "title": "使用Sequelize建立model",
          "slug": "使用sequelize建立model"
        }
      ],
      "lastUpdated": "11/29/2021, 2:22:20 PM"
    },
    {
      "title": "创建数据库",
      "frontmatter": {
        "actionText": "创建数据库 →",
        "actionLink": "/mysql/"
      },
      "regularPath": "/mysql/",
      "relativePath": "mysql/readme.md",
      "key": "v-4964e974",
      "path": "/mysql/",
      "headers": [
        {
          "level": 3,
          "title": "创建数据库",
          "slug": "创建数据库"
        }
      ],
      "lastUpdated": "11/20/2021, 6:30:57 PM"
    },
    {
      "title": "select查询语句",
      "frontmatter": {
        "title": "select查询语句",
        "date": "2021-11-20T00:00:00.000Z",
        "categories": [
          "frontend"
        ],
        "tags": [
          "mysql",
          "sql"
        ]
      },
      "regularPath": "/mysql/operate_sql.html",
      "relativePath": "mysql/operate_sql.md",
      "key": "v-09f44a2f",
      "path": "/mysql/operate_sql.html",
      "headers": [
        {
          "level": 2,
          "title": "select 查询语句",
          "slug": "select-查询语句"
        },
        {
          "level": 3,
          "title": "where 子句条件查询",
          "slug": "where-子句条件查询"
        },
        {
          "level": 3,
          "title": "not in,或者in",
          "slug": "not-in-或者in"
        },
        {
          "level": 3,
          "title": "带 not / between and  的范围查询",
          "slug": "带-not-between-and-的范围查询"
        },
        {
          "level": 3,
          "title": "like 匹配查询，模糊查询",
          "slug": "like-匹配查询-模糊查询"
        },
        {
          "level": 3,
          "title": "查询空值is null 或者 is not null 子句；",
          "slug": "查询空值is-null-或者-is-not-null-子句"
        },
        {
          "level": 3,
          "title": "and 多条件查询",
          "slug": "and-多条件查询"
        },
        {
          "level": 3,
          "title": "or 查询",
          "slug": "or-查询"
        },
        {
          "level": 3,
          "title": "distinct 去重复查询",
          "slug": "distinct-去重复查询"
        },
        {
          "level": 2,
          "title": "对查询结果排序",
          "slug": "对查询结果排序"
        },
        {
          "level": 3,
          "title": "分组查询",
          "slug": "分组查询"
        },
        {
          "level": 3,
          "title": "group by",
          "slug": "group-by"
        },
        {
          "level": 3,
          "title": "having",
          "slug": "having"
        },
        {
          "level": 3,
          "title": "with rollup， ifnull()",
          "slug": "with-rollup-ifnull"
        },
        {
          "level": 3,
          "title": "多字段分组",
          "slug": "多字段分组"
        },
        {
          "level": 3,
          "title": "group by 和 order by一起使用",
          "slug": "group-by-和-order-by一起使用"
        },
        {
          "level": 3,
          "title": "用limit 限制查询结果的数量",
          "slug": "用limit-限制查询结果的数量"
        },
        {
          "level": 2,
          "title": "使用集合函数查询",
          "slug": "使用集合函数查询"
        },
        {
          "level": 3,
          "title": "count()使用",
          "slug": "count-使用"
        },
        {
          "level": 3,
          "title": "avg()使用",
          "slug": "avg-使用"
        },
        {
          "level": 3,
          "title": "max()使用",
          "slug": "max-使用"
        },
        {
          "level": 3,
          "title": "min()使用",
          "slug": "min-使用"
        },
        {
          "level": 2,
          "title": "连表查询",
          "slug": "连表查询"
        },
        {
          "level": 3,
          "title": "内连接查询",
          "slug": "内连接查询"
        },
        {
          "level": 3,
          "title": "外连接查询",
          "slug": "外连接查询"
        },
        {
          "level": 3,
          "title": "复合条件连接查询",
          "slug": "复合条件连接查询"
        },
        {
          "level": 2,
          "title": "子查询",
          "slug": "子查询"
        },
        {
          "level": 3,
          "title": "带any ,some 关键字的子查询",
          "slug": "带any-some-关键字的子查询"
        },
        {
          "level": 3,
          "title": "带all 关键字查询",
          "slug": "带all-关键字查询"
        },
        {
          "level": 3,
          "title": "带exists 关键字的子查询",
          "slug": "带exists-关键字的子查询"
        },
        {
          "level": 3,
          "title": "带in 关键字的子查询",
          "slug": "带in-关键字的子查询"
        },
        {
          "level": 3,
          "title": "带比较运算符的子查询",
          "slug": "带比较运算符的子查询"
        },
        {
          "level": 2,
          "title": "union , union all合并查询结果",
          "slug": "union-union-all合并查询结果"
        },
        {
          "level": 2,
          "title": "为表和字段取别名",
          "slug": "为表和字段取别名"
        },
        {
          "level": 2,
          "title": "使用正则表达式查询",
          "slug": "使用正则表达式查询"
        },
        {
          "level": 3,
          "title": "以‘^’开头，匹配以特定字符或者字符串开头的文本。",
          "slug": "以-开头-匹配以特定字符或者字符串开头的文本。"
        },
        {
          "level": 3,
          "title": "查询以特定字符或者字符串结尾‘$’的记录",
          "slug": "查询以特定字符或者字符串结尾-的记录"
        },
        {
          "level": 3,
          "title": "用符合‘.’来代替字符串中的任意一个字符",
          "slug": "用符合-来代替字符串中的任意一个字符"
        },
        {
          "level": 3,
          "title": "使用‘*’ 和‘+’ 来匹配多个字符",
          "slug": "使用-和-来匹配多个字符"
        },
        {
          "level": 3,
          "title": "匹配指定字符串",
          "slug": "匹配指定字符串"
        },
        {
          "level": 3,
          "title": "匹配指定字符中的任意一个",
          "slug": "匹配指定字符中的任意一个"
        },
        {
          "level": 3,
          "title": "使用{m}或者{m,n}来指定字符串连续出现的次数",
          "slug": "使用-m-或者-m-n-来指定字符串连续出现的次数"
        }
      ],
      "lastUpdated": "11/29/2021, 2:22:20 PM"
    },
    {
      "frontmatter": {
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/"
      },
      "regularPath": "/nested/",
      "relativePath": "nested/README.md",
      "key": "v-1c4118c2",
      "path": "/nested/",
      "lastUpdated": "3/6/2021, 4:40:28 PM"
    },
    {
      "title": "node总结",
      "frontmatter": {
        "title": "node总结",
        "date": "2022-4-24",
        "categories": [
          "frontend"
        ],
        "tags": [
          "node",
          "ts"
        ]
      },
      "regularPath": "/node/",
      "relativePath": "node/README.md",
      "key": "v-3d2d673c",
      "path": "/node/",
      "lastUpdated": "4/24/2022, 5:39:33 PM"
    },
    {
      "title": "redis与cache区别",
      "frontmatter": {
        "title": "redis与cache区别",
        "date": "2022-4-29",
        "categories": [
          "frontend"
        ],
        "tags": [
          "node",
          "ArrayBuffer"
        ]
      },
      "regularPath": "/node/cache-redis.html",
      "relativePath": "node/cache-redis.md",
      "key": "v-cabb67e2",
      "path": "/node/cache-redis.html",
      "headers": [
        {
          "level": 3,
          "title": "概述",
          "slug": "概述"
        },
        {
          "level": 3,
          "title": "先看看redis和Cache的区别吧",
          "slug": "先看看redis和cache的区别吧"
        },
        {
          "level": 3,
          "title": "关于redis和memcache的不同",
          "slug": "关于redis和memcache的不同"
        },
        {
          "level": 3,
          "title": "cache 管理包",
          "slug": "cache-管理包"
        },
        {
          "level": 3,
          "title": "选择",
          "slug": "选择"
        },
        {
          "level": 3,
          "title": "cached介绍",
          "slug": "cached介绍"
        }
      ],
      "lastUpdated": "5/7/2022, 6:30:40 PM"
    },
    {
      "title": "创建脚手架",
      "frontmatter": {
        "title": "创建脚手架",
        "date": "2022-5-13",
        "categories": [
          "frontend"
        ],
        "tags": [
          "node",
          "ArrayBuffer"
        ]
      },
      "regularPath": "/node/cli.html",
      "relativePath": "node/cli.md",
      "key": "v-433d15af",
      "path": "/node/cli.html",
      "headers": [
        {
          "level": 2,
          "title": "安装yo",
          "slug": "安装yo"
        },
        {
          "level": 2,
          "title": "安装对应 generater",
          "slug": "安装对应-generater"
        },
        {
          "level": 2,
          "title": "yo 运行generator",
          "slug": "yo-运行generator"
        },
        {
          "level": 3,
          "title": "Yeoman Sub Generator",
          "slug": "yeoman-sub-generator"
        },
        {
          "level": 2,
          "title": "Yeoman 基本使用步骤",
          "slug": "yeoman-基本使用步骤"
        },
        {
          "level": 2,
          "title": "创建",
          "slug": "创建"
        }
      ]
    },
    {
      "title": "nest.js 总结",
      "frontmatter": {
        "title": "nest.js 总结",
        "date": "2022-4-29",
        "categories": [
          "frontend"
        ],
        "tags": [
          "node",
          "ArrayBuffer"
        ]
      },
      "regularPath": "/node/nest.js/start.html",
      "relativePath": "node/nest.js/start.md",
      "key": "v-56e676f8",
      "path": "/node/nest.js/start.html",
      "headers": [
        {
          "level": 3,
          "title": "简介",
          "slug": "简介"
        },
        {
          "level": 3,
          "title": "命令",
          "slug": "命令"
        }
      ],
      "lastUpdated": "5/7/2022, 6:30:40 PM"
    },
    {
      "title": "守护Node.js进程",
      "frontmatter": {
        "title": "守护Node.js进程",
        "date": "2022-4-24",
        "categories": [
          "frontend"
        ],
        "tags": [
          "node",
          "ArrayBuffer"
        ]
      },
      "regularPath": "/node/node_process.html",
      "relativePath": "node/node_process.md",
      "key": "v-6cf031ee",
      "path": "/node/node_process.html",
      "headers": [
        {
          "level": 3,
          "title": "Node.js开发的特点",
          "slug": "node-js开发的特点"
        },
        {
          "level": 3,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 3,
          "title": "基本使用",
          "slug": "基本使用"
        }
      ],
      "lastUpdated": "4/24/2022, 5:39:33 PM"
    },
    {
      "title": "Time Line",
      "frontmatter": {
        "isTimeLine": true,
        "sidebar": false,
        "isComment": false
      },
      "regularPath": "/timeLine/",
      "relativePath": "timeLine/README.md",
      "key": "v-d8ffd67c",
      "path": "/timeLine/",
      "headers": [
        {
          "level": 2,
          "title": "Time Line",
          "slug": "time-line"
        }
      ],
      "lastUpdated": "3/6/2021, 4:40:28 PM"
    },
    {
      "title": "H5",
      "frontmatter": {},
      "regularPath": "/web/H5/",
      "relativePath": "web/H5/README.md",
      "key": "v-92fb9f62",
      "path": "/web/H5/",
      "headers": [
        {
          "level": 3,
          "title": "H5",
          "slug": "h5"
        }
      ],
      "lastUpdated": "3/6/2021, 4:40:28 PM"
    },
    {
      "title": "svg",
      "frontmatter": {
        "title": "svg",
        "date": "2019-8-27",
        "categories": [
          "frontend"
        ],
        "tags": [
          "h5",
          "svg"
        ]
      },
      "regularPath": "/web/H5/svg.html",
      "relativePath": "web/H5/svg.md",
      "key": "v-5bc2f40e",
      "path": "/web/H5/svg.html",
      "lastUpdated": "3/6/2021, 4:40:28 PM"
    },
    {
      "title": "React",
      "frontmatter": {},
      "regularPath": "/web/React/",
      "relativePath": "web/React/README.md",
      "key": "v-05a5bba2",
      "path": "/web/React/",
      "lastUpdated": "3/6/2021, 4:40:28 PM"
    },
    {
      "title": "React + Ts 实现三子棋小游戏",
      "frontmatter": {
        "title": "React + Ts 实现三子棋小游戏",
        "date": "2019-9-12",
        "categories": [
          "frontend"
        ],
        "tags": [
          "react",
          "ts"
        ]
      },
      "regularPath": "/web/React/chess.html",
      "relativePath": "web/React/chess.md",
      "key": "v-01e106c2",
      "path": "/web/React/chess.html",
      "headers": [
        {
          "level": 2,
          "title": "游戏规则",
          "slug": "游戏规则"
        },
        {
          "level": 2,
          "title": "组件化",
          "slug": "组件化"
        },
        {
          "level": 2,
          "title": "开发棋子组件",
          "slug": "开发棋子组件"
        },
        {
          "level": 2,
          "title": "开发棋盘组件",
          "slug": "开发棋盘组件"
        },
        {
          "level": 2,
          "title": "开发游戏规则组件",
          "slug": "开发游戏规则组件"
        },
        {
          "level": 2,
          "title": "开发显示游戏状态的组件",
          "slug": "开发显示游戏状态的组件"
        },
        {
          "level": 2,
          "title": "收尾",
          "slug": "收尾"
        }
      ],
      "lastUpdated": "3/6/2021, 4:40:28 PM"
    },
    {
      "title": "useCallback的api适用",
      "frontmatter": {
        "title": "useCallback的api适用",
        "date": "2022-04-2",
        "categories": [
          "frontend"
        ],
        "tags": [
          "react",
          "ts"
        ]
      },
      "regularPath": "/web/React/useCallback-api.html",
      "relativePath": "web/React/useCallback-api.md",
      "key": "v-4abf3be2",
      "path": "/web/React/useCallback-api.html",
      "headers": [
        {
          "level": 3,
          "title": "useCallback问题和隐患并给出解决方案",
          "slug": "usecallback问题和隐患并给出解决方案"
        },
        {
          "level": 3,
          "title": "使用 useCallback 的场景",
          "slug": "使用-usecallback-的场景"
        },
        {
          "level": 3,
          "title": "案例",
          "slug": "案例"
        },
        {
          "level": 3,
          "title": "CodeReview 与修改",
          "slug": "codereview-与修改"
        },
        {
          "level": 3,
          "title": "哪些地方需要优化？",
          "slug": "哪些地方需要优化"
        },
        {
          "level": 3,
          "title": "哪些地方不规范？",
          "slug": "哪些地方不规范"
        },
        {
          "level": 3,
          "title": "修改代码",
          "slug": "修改代码"
        },
        {
          "level": 3,
          "title": "为什么出了问题",
          "slug": "为什么出了问题"
        },
        {
          "level": 3,
          "title": "如何解决",
          "slug": "如何解决"
        },
        {
          "level": 3,
          "title": "优化使用 ref 的体验",
          "slug": "优化使用-ref-的体验"
        },
        {
          "level": 3,
          "title": "思考我们最开始使用 useCallback 的理由",
          "slug": "思考我们最开始使用-usecallback-的理由"
        },
        {
          "level": 3,
          "title": "结论",
          "slug": "结论"
        }
      ],
      "lastUpdated": "5/7/2022, 6:30:40 PM"
    },
    {
      "title": "hooks useMemo",
      "frontmatter": {
        "title": "hooks useMemo",
        "date": "2022-05-7",
        "categories": [
          "frontend"
        ],
        "tags": [
          "react",
          "ts"
        ]
      },
      "regularPath": "/web/React/useMemo.html",
      "relativePath": "web/React/useMemo.md",
      "key": "v-db5c4e3c",
      "path": "/web/React/useMemo.html",
      "headers": [
        {
          "level": 3,
          "title": "",
          "slug": ""
        }
      ],
      "lastUpdated": "5/11/2022, 5:28:30 PM"
    },
    {
      "title": "高级前端进阶",
      "frontmatter": {},
      "regularPath": "/web/advanced/",
      "relativePath": "web/advanced/README.md",
      "key": "v-a1a12a22",
      "path": "/web/advanced/",
      "headers": [
        {
          "level": 2,
          "title": "高级前端进阶",
          "slug": "高级前端进阶"
        }
      ],
      "lastUpdated": "1/13/2022, 5:04:39 PM"
    },
    {
      "title": "面向对象继承",
      "frontmatter": {
        "title": "面向对象继承",
        "date": "2019-8-19",
        "categories": [
          "js面向对象继承解说"
        ],
        "tags": [
          "面向对象",
          "继承"
        ]
      },
      "regularPath": "/web/advanced/inherit.html",
      "relativePath": "web/advanced/inherit.md",
      "key": "v-86193a14",
      "path": "/web/advanced/inherit.html",
      "headers": [
        {
          "level": 3,
          "title": "",
          "slug": ""
        }
      ],
      "lastUpdated": "1/13/2022, 5:04:39 PM"
    },
    {
      "title": "调用栈--执行上下文",
      "frontmatter": {
        "title": "调用栈--执行上下文",
        "date": "2019-8-19",
        "categories": [
          "js调用栈之执行上下文"
        ],
        "tags": [
          "调用栈",
          "执行上下文"
        ]
      },
      "regularPath": "/web/advanced/executive.html",
      "relativePath": "web/advanced/executive.md",
      "key": "v-79af9248",
      "path": "/web/advanced/executive.html",
      "headers": [
        {
          "level": 3,
          "title": "简述",
          "slug": "简述"
        },
        {
          "level": 3,
          "title": "执行上下文栈（调用栈）",
          "slug": "执行上下文栈-调用栈"
        },
        {
          "level": 3,
          "title": "执行上下文",
          "slug": "执行上下文"
        },
        {
          "level": 3,
          "title": "对于每个执行上下文，都有三个重要属性：",
          "slug": "对于每个执行上下文-都有三个重要属性"
        },
        {
          "level": 3,
          "title": "全局上下文",
          "slug": "全局上下文"
        },
        {
          "level": 3,
          "title": "函数上下文",
          "slug": "函数上下文"
        },
        {
          "level": 3,
          "title": "思考题",
          "slug": "思考题"
        },
        {
          "level": 3,
          "title": "作用域",
          "slug": "作用域"
        },
        {
          "level": 3,
          "title": "作用域链",
          "slug": "作用域链"
        }
      ],
      "lastUpdated": "1/21/2022, 5:57:07 PM"
    },
    {
      "title": "原型链图解",
      "frontmatter": {
        "title": "原型链图解",
        "date": "2019-8-19",
        "categories": [
          "js面向对象原型链解说"
        ],
        "tags": [
          "面向对象",
          "原型链"
        ]
      },
      "regularPath": "/web/advanced/prototype.html",
      "relativePath": "web/advanced/prototype.md",
      "key": "v-3e6fdd30",
      "path": "/web/advanced/prototype.html",
      "headers": [
        {
          "level": 3,
          "title": "JS中的原型和原型链",
          "slug": "js中的原型和原型链"
        },
        {
          "level": 3,
          "title": "构造函数",
          "slug": "构造函数"
        },
        {
          "level": 3,
          "title": "原型",
          "slug": "原型"
        },
        {
          "level": 3,
          "title": "实例对象与原型对象关系",
          "slug": "实例对象与原型对象关系"
        },
        {
          "level": 3,
          "title": "继承与原型链",
          "slug": "继承与原型链"
        },
        {
          "level": 3,
          "title": "比较全面原型图",
          "slug": "比较全面原型图"
        }
      ],
      "lastUpdated": "1/13/2022, 5:04:39 PM"
    },
    {
      "title": "es6之ArrayBuffer",
      "frontmatter": {
        "title": "es6之ArrayBuffer",
        "date": "2019-8-23",
        "categories": [
          "frontend"
        ],
        "tags": [
          "es6",
          "ArrayBuffer"
        ]
      },
      "regularPath": "/web/es6/ArrayBuffer.html",
      "relativePath": "web/es6/ArrayBuffer.md",
      "key": "v-511ddc7c",
      "path": "/web/es6/ArrayBuffer.html",
      "headers": [
        {
          "level": 2,
          "title": "js操作二进制数据三兄弟",
          "slug": "js操作二进制数据三兄弟"
        },
        {
          "level": 2,
          "title": "设计的目的",
          "slug": "设计的目的"
        },
        {
          "level": 2,
          "title": "概念",
          "slug": "概念"
        },
        {
          "level": 2,
          "title": "在浏览器中",
          "slug": "在浏览器中"
        },
        {
          "level": 2,
          "title": "ArrayBuffer 的api",
          "slug": "arraybuffer-的api"
        },
        {
          "level": 3,
          "title": "返回所分配的内存区域的字节长度",
          "slug": "返回所分配的内存区域的字节长度"
        },
        {
          "level": 3,
          "title": "允许将内存区域的一部分复制生成一个新的ArrayBuffer对象",
          "slug": "允许将内存区域的一部分复制生成一个新的arraybuffer对象"
        },
        {
          "level": 3,
          "title": "返回整段内存区域对应的ArrayBuffer对象，只读",
          "slug": "返回整段内存区域对应的arraybuffer对象-只读"
        },
        {
          "level": 3,
          "title": "返回TypeArray数组占据的内存长度，单位位字节， 只读",
          "slug": "返回typearray数组占据的内存长度-单位位字节-只读"
        },
        {
          "level": 3,
          "title": "用于整段的复制，复制a的内容到b",
          "slug": "用于整段的复制-复制a的内容到b"
        }
      ],
      "lastUpdated": "11/9/2021, 5:39:03 PM"
    },
    {
      "title": "当你凝望大神的时候，大神也在凝望你",
      "frontmatter": {},
      "regularPath": "/web/es6/",
      "relativePath": "web/es6/README.md",
      "key": "v-766fc85d",
      "path": "/web/es6/",
      "lastUpdated": "3/6/2021, 4:40:28 PM"
    },
    {
      "title": "es7之修饰器",
      "frontmatter": {
        "title": "es7之修饰器",
        "date": "2019-8-17",
        "categories": [
          "frontend"
        ],
        "tags": [
          "es7",
          "修饰器"
        ]
      },
      "regularPath": "/web/es6/es7_decorator.html",
      "relativePath": "web/es6/es7_decorator.md",
      "key": "v-a8d476fc",
      "path": "/web/es6/es7_decorator.html",
      "lastUpdated": "3/6/2021, 4:40:28 PM"
    },
    {
      "title": "前端模块化",
      "frontmatter": {
        "title": "前端模块化",
        "date": "2021-11-09T00:00:00.000Z",
        "categories": [
          "frontend"
        ],
        "tags": [
          "cmd",
          "amd",
          "esm"
        ]
      },
      "regularPath": "/web/es6/front_end_modul.html",
      "relativePath": "web/es6/front_end_modul.md",
      "key": "v-0c94ce02",
      "path": "/web/es6/front_end_modul.html",
      "headers": [
        {
          "level": 2,
          "title": "背景",
          "slug": "背景"
        },
        {
          "level": 2,
          "title": "CommonJS",
          "slug": "commonjs"
        },
        {
          "level": 2,
          "title": "AMD",
          "slug": "amd"
        },
        {
          "level": 2,
          "title": "ESM",
          "slug": "esm"
        },
        {
          "level": 2,
          "title": "ESM 规范",
          "slug": "esm-规范"
        },
        {
          "level": 3,
          "title": "模块导出",
          "slug": "模块导出"
        },
        {
          "level": 3,
          "title": "模块导入",
          "slug": "模块导入"
        },
        {
          "level": 3,
          "title": "导入同时进行导出",
          "slug": "导入同时进行导出"
        },
        {
          "level": 2,
          "title": "ESM 与 CommonJS 的差异",
          "slug": "esm-与-commonjs-的差异"
        },
        {
          "level": 3,
          "title": "服务端",
          "slug": "服务端"
        }
      ],
      "lastUpdated": "11/9/2021, 5:39:03 PM"
    },
    {
      "title": "让你的项目使用Ts吧",
      "frontmatter": {
        "title": "让你的项目使用Ts吧",
        "date": "2019-8-29",
        "categories": [
          "frontend"
        ],
        "tags": [
          "ts"
        ]
      },
      "regularPath": "/web/es6/ts_config.html",
      "relativePath": "web/es6/ts_config.md",
      "key": "v-6fc3fde2",
      "path": "/web/es6/ts_config.html",
      "headers": [
        {
          "level": 2,
          "title": "why ?",
          "slug": "why"
        },
        {
          "level": 2,
          "title": "还在犹豫什么",
          "slug": "还在犹豫什么"
        },
        {
          "level": 2,
          "title": "本文不涉及框架内容，因为框架的cli已经帮你搭好了ts环境。。。",
          "slug": "本文不涉及框架内容-因为框架的cli已经帮你搭好了ts环境。。。"
        },
        {
          "level": 2,
          "title": "本文只教你如何在一个demo里搭建Ts环境，好了，我们开始吧",
          "slug": "本文只教你如何在一个demo里搭建ts环境-好了-我们开始吧"
        },
        {
          "level": 2,
          "title": "插播一条重要内容",
          "slug": "插播一条重要内容"
        },
        {
          "level": 2,
          "title": "ts和js分开",
          "slug": "ts和js分开"
        },
        {
          "level": 2,
          "title": "ts-node",
          "slug": "ts-node"
        },
        {
          "level": 2,
          "title": "nodemon",
          "slug": "nodemon"
        }
      ],
      "lastUpdated": "3/6/2021, 4:40:28 PM"
    },
    {
      "title": "面试题总结",
      "frontmatter": {},
      "regularPath": "/web/interview/",
      "relativePath": "web/interview/README.md",
      "key": "v-324f6d2a",
      "path": "/web/interview/",
      "lastUpdated": "4/1/2022, 1:27:01 PM"
    },
    {
      "title": "跨域造成原因和解决方法",
      "frontmatter": {
        "title": "跨域造成原因和解决方法",
        "date": "2022-4-1",
        "categories": [
          "frontend"
        ],
        "tags": [
          "react，vue，http",
          "ts"
        ]
      },
      "regularPath": "/web/interview/cross-domain.html",
      "relativePath": "web/interview/cross-domain.md",
      "key": "v-7511ec4c",
      "path": "/web/interview/cross-domain.html",
      "headers": [
        {
          "level": 3,
          "title": "跨域指？",
          "slug": "跨域指"
        },
        {
          "level": 3,
          "title": "跨域的解决方案",
          "slug": "跨域的解决方案"
        },
        {
          "level": 3,
          "title": "跨域请求如何携带 cookie",
          "slug": "跨域请求如何携带-cookie"
        }
      ],
      "lastUpdated": "4/1/2022, 1:27:01 PM"
    },
    {
      "title": "http和https知识点",
      "frontmatter": {
        "title": "http和https知识点",
        "date": "2022-5-13",
        "categories": [
          "frontend"
        ],
        "tags": [
          "react，vue，http",
          "ts"
        ]
      },
      "regularPath": "/web/interview/http_https.html",
      "relativePath": "web/interview/http_https.md",
      "key": "v-baa599d8",
      "path": "/web/interview/http_https.html",
      "headers": [
        {
          "level": 2,
          "title": "http",
          "slug": "http"
        },
        {
          "level": 2,
          "title": "https",
          "slug": "https"
        }
      ]
    },
    {
      "title": "面试题",
      "frontmatter": {
        "title": "面试题",
        "date": "2022-3-28",
        "categories": [
          "frontend"
        ],
        "tags": [
          "react，vue，http",
          "ts"
        ]
      },
      "regularPath": "/web/interview/interview.html",
      "relativePath": "web/interview/interview.md",
      "key": "v-4d283d22",
      "path": "/web/interview/interview.html",
      "lastUpdated": "5/7/2022, 6:30:40 PM"
    },
    {
      "title": "面试过程",
      "frontmatter": {},
      "regularPath": "/web/interview/notes.html",
      "relativePath": "web/interview/notes.md",
      "key": "v-4648f522",
      "path": "/web/interview/notes.html",
      "headers": [
        {
          "level": 2,
          "title": "网络层http",
          "slug": "网络层http"
        },
        {
          "level": 2,
          "title": "virtual DOM  好处/坏处",
          "slug": "virtual-dom-好处-坏处"
        },
        {
          "level": 2,
          "title": "vue3 优化",
          "slug": "vue3-优化"
        },
        {
          "level": 2,
          "title": "react与vue key作用",
          "slug": "react与vue-key作用"
        },
        {
          "level": 2,
          "title": "react hooks 替代 redux",
          "slug": "react-hooks-替代-redux"
        },
        {
          "level": 2,
          "title": "react fiber 原理",
          "slug": "react-fiber-原理"
        },
        {
          "level": 2,
          "title": "工程化优化打包，提高加载速度",
          "slug": "工程化优化打包-提高加载速度"
        },
        {
          "level": 2,
          "title": "未来规划",
          "slug": "未来规划"
        },
        {
          "level": 3,
          "title": "网站性能优化都有哪些点",
          "slug": "网站性能优化都有哪些点"
        }
      ],
      "lastUpdated": "5/11/2022, 5:28:30 PM"
    },
    {
      "title": "typescript",
      "frontmatter": {},
      "regularPath": "/web/ts/",
      "relativePath": "web/ts/README.md",
      "key": "v-5597620f",
      "path": "/web/ts/",
      "headers": [
        {
          "level": 2,
          "title": "typescript",
          "slug": "typescript"
        }
      ],
      "lastUpdated": "1/11/2022, 3:57:00 PM"
    },
    {
      "title": "ts安装",
      "frontmatter": {
        "title": "ts安装"
      },
      "regularPath": "/web/ts/install.html",
      "relativePath": "web/ts/install.md",
      "key": "v-324bfd7c",
      "path": "/web/ts/install.html",
      "lastUpdated": "1/11/2022, 3:57:00 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/web/vue/",
      "relativePath": "web/vue/README.md",
      "key": "v-05413ae1",
      "path": "/web/vue/",
      "lastUpdated": "3/6/2021, 4:40:28 PM"
    },
    {
      "title": "常用composition API",
      "frontmatter": {
        "title": "常用composition API",
        "date": "2021-11-25T00:00:00.000Z",
        "categories": [
          "frontend"
        ],
        "tags": [
          "vue3",
          "索引"
        ]
      },
      "regularPath": "/web/vue/vue3_intro.html",
      "relativePath": "web/vue/vue3_intro.md",
      "key": "v-6107a692",
      "path": "/web/vue/vue3_intro.html",
      "headers": [
        {
          "level": 2,
          "title": "组合式 API",
          "slug": "组合式-api"
        },
        {
          "level": 3,
          "title": "5. reactive 对比 ref",
          "slug": "_5-reactive-对比-ref"
        },
        {
          "level": 3,
          "title": "6.setup的两个注意点",
          "slug": "_6-setup的两个注意点"
        },
        {
          "level": 3,
          "title": "7.计算属性与监视",
          "slug": "_7-计算属性与监视"
        },
        {
          "level": 3,
          "title": "8生命周期",
          "slug": "_8生命周期"
        },
        {
          "level": 3,
          "title": "9.自定义hook函数",
          "slug": "_9-自定义hook函数"
        },
        {
          "level": 3,
          "title": "toRef",
          "slug": "toref"
        },
        {
          "level": 3,
          "title": "其他composition API",
          "slug": "其他composition-api"
        },
        {
          "level": 3,
          "title": "vue3其他调整",
          "slug": "vue3其他调整"
        }
      ],
      "lastUpdated": "3/24/2022, 3:32:55 PM"
    },
    {
      "title": "文档说明",
      "frontmatter": {},
      "regularPath": "/zh/guide/",
      "relativePath": "zh/guide/README.md",
      "key": "v-4ab03f75",
      "path": "/zh/guide/",
      "headers": [
        {
          "level": 3,
          "title": "文档说明",
          "slug": "文档说明"
        }
      ],
      "lastUpdated": "10/25/2021, 3:10:19 PM"
    },
    {
      "title": "vuePress部署到Github Page",
      "frontmatter": {
        "title": "vuePress部署到Github Page",
        "date": "2019-8-19",
        "categories": [
          "frontend"
        ],
        "tags": [
          "vuePress",
          "部署"
        ]
      },
      "regularPath": "/web/vue/vuePress_deploy.html",
      "relativePath": "web/vue/vuePress_deploy.md",
      "key": "v-b37131fc",
      "path": "/web/vue/vuePress_deploy.html",
      "headers": [
        {
          "level": 2,
          "title": "小坑",
          "slug": "小坑"
        },
        {
          "level": 2,
          "title": "1.1",
          "slug": "_1-1"
        },
        {
          "level": 2,
          "title": "1.2",
          "slug": "_1-2"
        }
      ],
      "lastUpdated": "3/6/2021, 4:40:28 PM"
    }
  ],
  "themeConfig": {
    "huawei": true,
    "type": "blog",
    "author": "Hamlin",
    "valineConfig": {
      "appId": "20uttEi9BN7qb7fMVhJwCEoc-gzGzoHsz",
      "appKey": "W2mkX4DhUukTDsfQeHi7mzQu",
      "notify": false,
      "verify": false,
      "avatar": "mp",
      "placeholder": "填写邮箱可以收到回复提醒哦",
      "visitor": true
    },
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "导航栏配置",
        "items": [
          {
            "text": "自动读取",
            "link": "/guide/vue/"
          },
          {
            "text": "自定义",
            "link": "/guide/ts/"
          }
        ]
      },
      {
        "text": "错误总结",
        "items": [
          {
            "text": "github",
            "link": "/error/"
          }
        ]
      },
      {
        "text": "前端",
        "link": "/web/",
        "items": [
          {
            "text": "es6",
            "link": "/web/es6/"
          },
          {
            "text": "vue",
            "link": "/web/vue/"
          },
          {
            "text": "H5",
            "link": "/web/H5/"
          },
          {
            "text": "React",
            "link": "/web/React/"
          },
          {
            "text": "ts",
            "link": "/web/ts/"
          },
          {
            "text": "进阶系列",
            "link": "/web/advanced/"
          },
          {
            "text": "面试题",
            "link": "/web/interview/"
          }
        ]
      },
      {
        "text": "nodejs",
        "link": "/node/"
      },
      {
        "text": "mysql",
        "link": "/mysql/"
      },
      {
        "text": "java",
        "link": "/java/"
      },
      {
        "text": "时间线",
        "link": "/timeLine/",
        "icon": "reco-date"
      },
      {
        "text": "友链",
        "link": "/friendLink/"
      },
      {
        "text": "关于",
        "link": "/nested/",
        "icon": "account_circle"
      }
    ],
    "sidebar": {
      "/web/es6/": [
        "es7_decorator",
        "ArrayBuffer",
        "ts_config",
        "front_end_modul"
      ],
      "/web/vue/": [
        "vuePress_deploy",
        {
          "title": "vue3 指导",
          "collapsable": true,
          "children": [
            "vue3_intro"
          ]
        }
      ],
      "/node/": [
        "node_process",
        {
          "title": "redis与cache区别",
          "collapsable": true,
          "children": [
            "cache-redis"
          ]
        },
        "cli"
      ],
      "/web/H5/": [
        "svg"
      ],
      "/web/React/": [
        {
          "title": "hooks api学习",
          "collapsable": true,
          "children": [
            "useCallback-api"
          ]
        },
        {
          "title": "实现三子棋小游戏 ",
          "collapsable": true,
          "children": [
            "chess"
          ]
        }
      ],
      "/web/ts/": [
        "install"
      ],
      "/web/interview/": [
        "notes",
        {
          "title": "跨域的解决方案",
          "collapsable": true,
          "children": [
            "cross-domain"
          ]
        }
      ],
      "/mysql/": [
        "dowloadAndinstall",
        "introduce",
        "db_base_table",
        "date_type",
        "operate_sql",
        "insert_update",
        "indexes",
        "node_engine"
      ],
      "/guide/vue/": [
        "test01",
        "test02",
        "test03"
      ],
      "/guide/ts/": [
        {
          "title": "Typescript 学习",
          "collapsable": true,
          "children": [
            "test01",
            "test02",
            "test03"
          ]
        }
      ],
      "/error/": [
        {
          "title": "github 提交错误",
          "collapsable": true,
          "children": [
            "git_error"
          ]
        }
      ]
    },
    "blogConfig": {
      "category": {
        "location": 6,
        "text": "Category"
      },
      "tag": {
        "location": 5,
        "text": "Tag"
      }
    },
    "sidebarDepth": 3,
    "algolia": {
      "apiKey": "<API_KEY>",
      "indexName": "<INDEX_NAME>"
    },
    "lastUpdated": "Last Updated",
    "repo": "ChaselLHL/myBlog",
    "docsDir": "docs",
    "editLinks": true,
    "editLinkText": "在 GitHub 上编辑此页",
    "serviceWorker": {
      "updatePopup": {
        "message": "发现新内容可用.",
        "buttonText": "刷新"
      }
    }
  }
}